before_build:
  - cmd: choco install wget
  - wget -nv -nc https://download.microsoft.com/download/3/7/F/37F1CA21-E5EE-4309-9714-E914703ED05A/dotnet-dev-win-x64.2.0.0-preview1-005977.exe
  - dotnet-dev-win-x64.2.0.0-preview1-005977.exe /install /quiet /log dotnetinstall.log
  - ps: Push-AppveyorArtifact "dotnetinstall.log"
  - ps: .\clone-mono.ps1

build_script:
  - cmd: dotnet restore
  - cmd: dotnet build
  - cmd: dotnet pack --version-suffix r%APPVEYOR_BUILD_NUMBER% -c Release
  - ps: Push-AppveyorArtifact "src\CoreCompat.System.Drawing\bin\Release\CoreCompat.System.Drawing.v2.5.2.0-preview1-r$($env:APPVEYOR_BUILD_NUMBER).nupkg"

test_script:
  - cmd: dotnet test --filter "TestCategory != NotWorking" test/CoreCompat.System.Drawing.Tests/CoreCompat.System.Drawing.Tests.csproj 
